/**
 * Regenerates the self-hosted web fonts in public/fonts and src/fonts.css.
 *
 * We serve the fonts ourselves because fonts.googleapis.com times out on some
 * Indian networks: the page then rendered in a fallback face and logged a
 * console error on every load. Run this only when the type stack changes.
 *
 *   node scripts/fonts.mjs
 */
import fs from 'node:fs';

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36';
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@600;700;800&display=swap';

/** Only the subsets the site's content actually uses. */
const KEEP = ['latin', 'latin-ext'];

const subsetOf = (range) => {
  if (range.includes('U+0000-00FF')) return 'latin';
  if (range.includes('U+0460-052F')) return 'cyrillic-ext';
  if (range.includes('U+0400-045F')) return 'cyrillic';
  if (range.includes('U+1F00-1FFF')) return 'greek-ext';
  if (range.includes('U+0370-0377')) return 'greek';
  if (range.includes('U+1EA0-1EF9')) return 'vietnamese';
  if (range.includes('U+0100-02BA')) return 'latin-ext';
  return 'other';
};

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

const faces = new Map();
for (const [, body] of css.matchAll(/@font-face\s*\{([^}]+)\}/g)) {
  const family = /font-family:\s*'([^']+)'/.exec(body)[1];
  const weight = Number(/font-weight:\s*(\d+)/.exec(body)[1]);
  const src = /url\((https:[^)]+)\)/.exec(body)[1];
  const range = /unicode-range:\s*([^;]+);/.exec(body)[1].trim();
  const subset = subsetOf(range);
  if (!KEEP.includes(subset)) continue;
  const key = `${family}|${subset}`;
  if (!faces.has(key)) faces.set(key, { family, subset, src, range, weights: new Set() });
  faces.get(key).weights.add(weight);
  // Google serves one variable file per subset, so the src must not vary.
  if (faces.get(key).src !== src)
    throw new Error(`${key} is served as separate static files; the weight range below would be wrong`);
}

fs.mkdirSync('public/fonts', { recursive: true });
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-');

let out = `/* -------------------------------------------------------- web fonts ---
   Self-hosted rather than fetched from fonts.googleapis.com, which times
   out on some Indian networks -- the page then rendered in a fallback face
   and logged a failed request on every load. Both families are variable,
   so one file per subset covers every weight the site uses.

   Generated by scripts/fonts.mjs. Do not edit by hand.
   ------------------------------------------------------------------------ */
`;

for (const face of faces.values()) {
  const name = `${slug(face.family)}-${face.subset}.woff2`;
  const buf = Buffer.from(
    await (await fetch(face.src, { headers: { 'User-Agent': UA } })).arrayBuffer(),
  );
  fs.writeFileSync(`public/fonts/${name}`, buf);
  const w = [...face.weights].sort((a, b) => a - b);
  console.log(`${name.padEnd(34)} ${(buf.length / 1024).toFixed(1).padStart(6)} KB  weights ${w.join(',')}`);
  out += `
@font-face {
  font-family: "${face.family}";
  font-style: normal;
  font-weight: ${w[0]} ${w[w.length - 1]};
  font-display: swap;
  src: url("/fonts/${name}") format("woff2");
  unicode-range: ${face.range};
}
`;
}

fs.writeFileSync('src/fonts.css', out.trimStart(), 'utf8');
console.log('wrote src/fonts.css');
